# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
# What combinations to test
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: >-
      if ($env:nodejs_version -eq "0.10") {
        npm -g install npm@3
        $env:PATH="$env:APPDATA\npm;$env:PATH"
      }
  - npm install
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test
build: off
clone_depth: 10
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json
